# Generated by Django 4.2.6 on 2023-10-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_vender_remove_stock_receive_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='receive_by',
            new_name='subtotal',
        ),
    ]
